### ISSUE TITLE
Limit not working + bracket organization missing

### ISSUE THREAD

**Issue by defidude** [sdelgadoc/download-tweets-ai-text-gen-plus#2]
I've set a limit to only download a max of 10,000 tweets per user, and the limit shows in the command line when downloading the tweets (x/10000), however after letting it run it's become apparent the limit isn't working, I have over 90,000 tweets when I should only have ~40,000-50,000.

I have it including replies as well if that matters.

________________

Also I noticed in the CSV the tweets are all separated by a blank line, example:

`Tweet1`

`Tweet2`

`Tweet3`

However in the old edition the tweets were separate with brackets, I'm assuming so GPT2 simple can read them properly, like so:

`['Tweet1']`
`['Tweet2']`
`['Tweet3']`

**Comment by sdelgadoc** [comment]
I tested the code, and was not able to reproduce the issue.  How are you measuring the number of tweets?  If you are using number of lines in the file, this metric won't match to the number of tweets because some tweets have multiple lines.

To measure the number of tweets, read the file using [Python's CSV reader](https://docs.python.org/3/library/csv.html).  This is the library used by this code to store the tweets to file, and by gpt-2-simple to read input files.

The difference with how tweets are separated was a bug in previous versions in the code.  Previously, the code generated tweets strings surrounded by brackets.  So, gpt-2 would generate tweets surrounded by brackets, and then the user would need to remove them.

In this version, the code doesn't surround the tweet strings with brackets to avoid having to remove them after gpt-2 generation.

**Comment by defidude** [comment]
You’re right, duh! I was counting the blank lines as well haha.

Also good to know the brackets aren’t needed, so it should be working as
needed (though it seems like it’s taking extremely long compared to
previous iterations).

Thanks once again for the help, will close this issue when I get back to my
computer.

**Comment by sdelgadoc** [comment]
For future reference on performance, I am getting 8.7 iterations (tweets) per second when I download all tweets from my Twitter account

**Comment by defidude** [comment]
Hm, that’s close to what I use to receive (above 5) however now I’m getting
~1.5/s, and for what it’s worth 4 of the 7 accounts I’ve exported were
exactly 1.54s/it, (another 1.59).

Wonder what’s limiting me, let alone at such a static rate it seems..
